name: Crawl Exchange Rates
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Run crawl once
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          NODE_ENV: production
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: node src/scripts/run-crawl-once.js
